### ISSUE TITLE
Website: 'NEWS' tab causes download

### ISSUE THREAD

**Issue by njh** [libcheck/check#10]
When I click on the 'NEWS' tab on the check website, in Chrome on Mac OS X, it causes it to download the file instead of viewing it.

Fetching the page with curl shows that the MIME type is 'application/octet-stream'.

    $ curl -v 'http://libcheck.github.io/check/NEWS'
    *   Trying 185.31.19.133...
    * Connected to libcheck.github.io (185.31.19.133) port 80 (#0)
    > GET /check/NEWS HTTP/1.1
    > Host: libcheck.github.io
    > User-Agent: curl/7.44.0
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Server: GitHub.com
    < Content-Type: application/octet-stream
    < Last-Modified: Thu, 24 Dec 2015 22:16:38 GMT
    < Access-Control-Allow-Origin: *
    < Expires: Fri, 25 Dec 2015 23:53:16 GMT
    < Cache-Control: max-age=600
    < X-GitHub-Request-Id: B91F1319:2F47:22CE40CE:567DD493
    < Content-Length: 20291
    < Accept-Ranges: bytes
    < Date: Fri, 25 Dec 2015 23:43:16 GMT
    < Via: 1.1 varnish
    < Age: 0
    < Connection: keep-alive
    < X-Served-By: cache-lhr6333-LHR
    < X-Cache: MISS
    < X-Cache-Hits: 0
    < X-Timer: S1451086996.058975,VS0,VE197
    < Vary: Accept-Encoding
    < X-Fastly-Request-ID: b7683b36740a99519ba7343452e15b5ffceae2c4
    <

**Comment by brarcher** [comment]
Well, that stinks. The same thing happens with the LGPL license, and also on other browsers besides Chrome.

According to this:

http://stackoverflow.com/questions/15951012/can-mime-types-of-github-pages-files-be-configured

it seems that GitHub is unable to determine the mimetype of the files because they do not have an extension, and fall back to application/octet-stream. 

I attempted to set the target of the link to open in a new browser tab, hoping that this would convince a browser to not download the file. 

http://www.w3schools.com/tags/att_a_target.asp

However, the browser still downloaded the file. Example here:

http://brarcher.github.io/check/

Without adding the extension of these files, I'm not sure of a way to resolve this, as the issue is on GitHub's side.

**Comment by ladar** [comment]
I believe there is a way. You can create a `.gitattributes` file, and then specify which files, like NEWS, etc, are in fact text files, and not binary blobs. See this URL for details on the syntax:

https://github.com/git/git/blob/master/Documentation/gitattributes.txt

I should note that I spent quite a bit of time trying to use the `.gitattribtes` file to force GitHub into displaying my project `README` file as Markdown. The attributes were respected when I viewed the individual file, but I never could get it to render the style information on the project page. 

That's a long way of saying, your mileage may vary.

**Comment by sskras** [comment]
Looks like it was fixed in the past, since now the `NEWS` tab open the plain text in my Chrome.

The CLI output got a bit different, at least because we are on SSL. 
<details> <summary> The <code>curl</code> log for <a href="https://libcheck.github.io/check/NEWS">https://libcheck.github.io/check/NEWS</a>: </summary> <br />

```sh
$ curl -v 'https://libcheck.github.io/check/NEWS' 
*   Trying 185.199.108.153:443...
* Connected to libcheck.github.io (185.199.108.153) port 443 (#0)
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2660 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.github.io
*  start date: Apr  6 23:32:36 2026 GMT
*  expire date: Jul  5 23:32:35 2026 GMT
*  subjectAltName: host "libcheck.github.io" matched cert's "*.github.io"
*  issuer: C=US; O=Let's Encrypt; CN=R12
*  SSL certificate verify ok.
} [5 bytes data]
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /check/NEWS]
* h2h3 [:scheme: https]
* h2h3 [:authority: libcheck.github.io]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x557280a357f0)
} [5 bytes data]
> GET /check/NEWS HTTP/2
> Host: libcheck.github.io
> user-agent: curl/7.88.1
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [193 bytes data]
< HTTP/2 200 
< server: GitHub.com
< content-type: application/octet-stream
< last-modified: Fri, 16 Apr 2021 16:26:13 GMT
< access-control-allow-origin: *
< etag: "6079baa5-5e76"
< expires: Sat, 13 Jun 2026 10:32:17 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: D310:3545FF:2BE7B35:2C69292:6A2D2F59
< accept-ranges: bytes
< date: Sat, 13 Jun 2026 10:57:06 GMT
< via: 1.1 varnish
< age: 120
< x-served-by: cache-hel1410022-HEL
< x-cache: HIT
< x-cache-hits: 1
< x-timer: S1781348226.399371,VS0,VE1
< vary: Accept-Encoding
< x-fastly-request-id: 338412806e89e1802da083c02cc5e9dbec061a49
< content-length: 24182
< 
{ [1006 bytes data]
* Connection #0 to host libcheck.github.io left intact
```
</details>

Can this be closed? :)

**Comment by njh** [comment]
I am still seeing `content-type: application/octet-stream` when requesting https://libcheck.github.io/check/NEWS.
And it is still downloading it as a file in Safari.
